# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/TensorGenerator/Other/GUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1275, 848)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.TabWidget.setObjectName("TabWidget")
        self.InputTab = QtWidgets.QWidget()
        self.InputTab.setObjectName("InputTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.InputTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AddGroup = QtWidgets.QGroupBox(self.InputTab)
        self.AddGroup.setObjectName("AddGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.AddGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.AddDirectoryLine = QtWidgets.QLineEdit(self.AddGroup)
        self.AddDirectoryLine.setObjectName("AddDirectoryLine")
        self.gridLayout.addWidget(self.AddDirectoryLine, 1, 2, 1, 1)
        self.AddDirectoryLabel = QtWidgets.QLabel(self.AddGroup)
        self.AddDirectoryLabel.setObjectName("AddDirectoryLabel")
        self.gridLayout.addWidget(self.AddDirectoryLabel, 0, 2, 1, 1)
        self.AddNameLabel = QtWidgets.QLabel(self.AddGroup)
        self.AddNameLabel.setObjectName("AddNameLabel")
        self.gridLayout.addWidget(self.AddNameLabel, 0, 0, 1, 1)
        self.BrowseAddDirectoryButton = QtWidgets.QPushButton(self.AddGroup)
        self.BrowseAddDirectoryButton.setObjectName("BrowseAddDirectoryButton")
        self.gridLayout.addWidget(self.BrowseAddDirectoryButton, 1, 3, 1, 1)
        self.AddNameLine = QtWidgets.QLineEdit(self.AddGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddNameLine.sizePolicy().hasHeightForWidth())
        self.AddNameLine.setSizePolicy(sizePolicy)
        self.AddNameLine.setObjectName("AddNameLine")
        self.gridLayout.addWidget(self.AddNameLine, 1, 0, 1, 1)
        self.AddButton = QtWidgets.QPushButton(self.AddGroup)
        self.AddButton.setObjectName("AddButton")
        self.gridLayout.addWidget(self.AddButton, 1, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.AddGroup)
        self.ClassesGroup = QtWidgets.QGroupBox(self.InputTab)
        self.ClassesGroup.setObjectName("ClassesGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ClassesGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ClassesScrollArea = QtWidgets.QScrollArea(self.ClassesGroup)
        self.ClassesScrollArea.setWidgetResizable(True)
        self.ClassesScrollArea.setObjectName("ClassesScrollArea")
        self.ClassesScrollAreaWidgets = QtWidgets.QWidget()
        self.ClassesScrollAreaWidgets.setGeometry(QtCore.QRect(0, 0, 1207, 400))
        self.ClassesScrollAreaWidgets.setObjectName("ClassesScrollAreaWidgets")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.ClassesScrollAreaWidgets)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ClassesList = QtWidgets.QListWidget(self.ClassesScrollAreaWidgets)
        self.ClassesList.setObjectName("ClassesList")
        self.horizontalLayout_2.addWidget(self.ClassesList)
        self.ClassesScrollArea.setWidget(self.ClassesScrollAreaWidgets)
        self.horizontalLayout.addWidget(self.ClassesScrollArea)
        self.verticalLayout_2.addWidget(self.ClassesGroup)
        self.PreferencesGroup = QtWidgets.QGroupBox(self.InputTab)
        self.PreferencesGroup.setObjectName("PreferencesGroup")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.PreferencesGroup)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ResizeGroup = QtWidgets.QGroupBox(self.PreferencesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResizeGroup.sizePolicy().hasHeightForWidth())
        self.ResizeGroup.setSizePolicy(sizePolicy)
        self.ResizeGroup.setObjectName("ResizeGroup")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.ResizeGroup)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ResizeHeightSpin = QtWidgets.QSpinBox(self.ResizeGroup)
        self.ResizeHeightSpin.setObjectName("ResizeHeightSpin")
        self.horizontalLayout_4.addWidget(self.ResizeHeightSpin)
        self.ResizeXLabel = QtWidgets.QLabel(self.ResizeGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResizeXLabel.sizePolicy().hasHeightForWidth())
        self.ResizeXLabel.setSizePolicy(sizePolicy)
        self.ResizeXLabel.setObjectName("ResizeXLabel")
        self.horizontalLayout_4.addWidget(self.ResizeXLabel)
        self.ResizeWidthSpin = QtWidgets.QSpinBox(self.ResizeGroup)
        self.ResizeWidthSpin.setObjectName("ResizeWidthSpin")
        self.horizontalLayout_4.addWidget(self.ResizeWidthSpin)
        self.horizontalLayout_9.addWidget(self.ResizeGroup)
        self.CropGroup = QtWidgets.QGroupBox(self.PreferencesGroup)
        self.CropGroup.setObjectName("CropGroup")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.CropGroup)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.CropDimensionGroup = QtWidgets.QGroupBox(self.CropGroup)
        self.CropDimensionGroup.setObjectName("CropDimensionGroup")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.CropDimensionGroup)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ResizeDimensionHeightSpin = QtWidgets.QSpinBox(self.CropDimensionGroup)
        self.ResizeDimensionHeightSpin.setObjectName("ResizeDimensionHeightSpin")
        self.horizontalLayout_5.addWidget(self.ResizeDimensionHeightSpin)
        self.ResizeDimensionXLabel = QtWidgets.QLabel(self.CropDimensionGroup)
        self.ResizeDimensionXLabel.setObjectName("ResizeDimensionXLabel")
        self.horizontalLayout_5.addWidget(self.ResizeDimensionXLabel)
        self.ResizeDimensionWidthSpin = QtWidgets.QSpinBox(self.CropDimensionGroup)
        self.ResizeDimensionWidthSpin.setObjectName("ResizeDimensionWidthSpin")
        self.horizontalLayout_5.addWidget(self.ResizeDimensionWidthSpin)
        self.horizontalLayout_7.addWidget(self.CropDimensionGroup)
        self.CropPositionGroup = QtWidgets.QGroupBox(self.CropGroup)
        self.CropPositionGroup.setObjectName("CropPositionGroup")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.CropPositionGroup)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.CropPositionXSpin = QtWidgets.QSpinBox(self.CropPositionGroup)
        self.CropPositionXSpin.setObjectName("CropPositionXSpin")
        self.horizontalLayout_6.addWidget(self.CropPositionXSpin)
        self.CropPositionXLabel = QtWidgets.QLabel(self.CropPositionGroup)
        self.CropPositionXLabel.setObjectName("CropPositionXLabel")
        self.horizontalLayout_6.addWidget(self.CropPositionXLabel)
        self.CropPositionYSpin = QtWidgets.QSpinBox(self.CropPositionGroup)
        self.CropPositionYSpin.setObjectName("CropPositionYSpin")
        self.horizontalLayout_6.addWidget(self.CropPositionYSpin)
        self.horizontalLayout_7.addWidget(self.CropPositionGroup)
        self.horizontalLayout_9.addWidget(self.CropGroup)
        self.PercentagesGroup = QtWidgets.QGroupBox(self.PreferencesGroup)
        self.PercentagesGroup.setObjectName("PercentagesGroup")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.PercentagesGroup)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.PercentagesTrainingLabel = QtWidgets.QLabel(self.PercentagesGroup)
        self.PercentagesTrainingLabel.setObjectName("PercentagesTrainingLabel")
        self.horizontalLayout_8.addWidget(self.PercentagesTrainingLabel)
        self.PercentagesTrainSpin = QtWidgets.QDoubleSpinBox(self.PercentagesGroup)
        self.PercentagesTrainSpin.setObjectName("PercentagesTrainSpin")
        self.horizontalLayout_8.addWidget(self.PercentagesTrainSpin)
        self.PercentagesTestLabel = QtWidgets.QLabel(self.PercentagesGroup)
        self.PercentagesTestLabel.setObjectName("PercentagesTestLabel")
        self.horizontalLayout_8.addWidget(self.PercentagesTestLabel)
        self.PercentagesTestSpin = QtWidgets.QDoubleSpinBox(self.PercentagesGroup)
        self.PercentagesTestSpin.setObjectName("PercentagesTestSpin")
        self.horizontalLayout_8.addWidget(self.PercentagesTestSpin)
        self.horizontalLayout_9.addWidget(self.PercentagesGroup)
        self.verticalLayout_2.addWidget(self.PreferencesGroup)
        self.OutputGroup = QtWidgets.QGroupBox(self.InputTab)
        self.OutputGroup.setObjectName("OutputGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.OutputGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.OutputDirectoryLabel = QtWidgets.QLabel(self.OutputGroup)
        self.OutputDirectoryLabel.setObjectName("OutputDirectoryLabel")
        self.horizontalLayout_3.addWidget(self.OutputDirectoryLabel)
        self.OutputDirectoryLine = QtWidgets.QLineEdit(self.OutputGroup)
        self.OutputDirectoryLine.setObjectName("OutputDirectoryLine")
        self.horizontalLayout_3.addWidget(self.OutputDirectoryLine)
        self.OutputBrowseButton = QtWidgets.QPushButton(self.OutputGroup)
        self.OutputBrowseButton.setObjectName("OutputBrowseButton")
        self.horizontalLayout_3.addWidget(self.OutputBrowseButton)
        self.verticalLayout_2.addWidget(self.OutputGroup)
        self.StartButton = QtWidgets.QPushButton(self.InputTab)
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_2.addWidget(self.StartButton)
        self.TabWidget.addTab(self.InputTab, "")
        self.NetTab = QtWidgets.QWidget()
        self.NetTab.setObjectName("NetTab")
        self.TabWidget.addTab(self.NetTab, "")
        self.verticalLayout.addWidget(self.TabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.InputTab.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.AddGroup.setTitle(_translate("MainWindow", "Añadir clase"))
        self.AddDirectoryLabel.setText(_translate("MainWindow", "Directorio:"))
        self.AddNameLabel.setText(_translate("MainWindow", "Nombre:"))
        self.BrowseAddDirectoryButton.setText(_translate("MainWindow", "Buscar"))
        self.AddButton.setText(_translate("MainWindow", "Añadir"))
        self.ClassesGroup.setTitle(_translate("MainWindow", "Clases"))
        self.PreferencesGroup.setTitle(_translate("MainWindow", "Preferencias"))
        self.ResizeGroup.setTitle(_translate("MainWindow", "Redimensionar a"))
        self.ResizeXLabel.setText(_translate("MainWindow", "x"))
        self.CropGroup.setTitle(_translate("MainWindow", "Recortar a"))
        self.CropDimensionGroup.setTitle(_translate("MainWindow", "Dimensiones"))
        self.ResizeDimensionXLabel.setText(_translate("MainWindow", "x"))
        self.CropPositionGroup.setTitle(_translate("MainWindow", "Posición"))
        self.CropPositionXLabel.setText(_translate("MainWindow", "x"))
        self.PercentagesGroup.setTitle(_translate("MainWindow", "Porcentages"))
        self.PercentagesTrainingLabel.setText(_translate("MainWindow", "Entrenamiento:"))
        self.PercentagesTestLabel.setText(_translate("MainWindow", "Test:"))
        self.OutputGroup.setTitle(_translate("MainWindow", "Salida"))
        self.OutputDirectoryLabel.setText(_translate("MainWindow", "Directorio:"))
        self.OutputBrowseButton.setText(_translate("MainWindow", "Buscar"))
        self.StartButton.setText(_translate("MainWindow", "Empezar"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.InputTab), _translate("MainWindow", "Preparación previa"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.NetTab), _translate("MainWindow", "Entrenamiento"))

